package view.Vendedor;

import dto.Usuario;
import dto.Vendedor;
import dao.UsuarioDAO;
import dao.VendedorDAO;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
/**
 
 * @author user
 */
public class VendedorRegister_Modf extends javax.swing.JDialog {
    private JComboBox<Usuario> cmbUsuario;
    private Usuario usuario;
    private VendedorView vendedorView;
    private boolean isModify;
    private int idVendedor;
    /**
     * Creates new form VendedorPrueba
     */
    public VendedorRegister_Modf(java.awt.Frame parent, Usuario usuario, VendedorView vendedorView, boolean isModify, int id) {
        super(parent, isModify ? "Modificar Vendedor" : "Registro de Vendedor", true);
        
        this.usuario = usuario;
        this.vendedorView = vendedorView; 
        this.isModify = isModify;
        this.idVendedor = id;
        initComponents();
        inicio(parent);

        configureUsuarios();
        if (isModify) {
            loadVendedorData();
        }
        setLocationRelativeTo(null);

    }
    
   private void inicio(Frame parent) {
    cmbUsuario = new JComboBox<>();
    panel1.add(cmbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 220, -1));
    cmbUsuario.setVisible(true);
    cmbUsuario.setPreferredSize(new Dimension(220, 30));
    cmbUsuario.setSize(220, 30);
    panel1.setComponentZOrder(cmbUsuario, 0); // Traer al frente

    
    spnInicio.setEditor(new JSpinner.DateEditor(spnInicio, "dd/MM/yyyy"));
    spnFin.setEditor(new JSpinner.DateEditor(spnFin, "dd/MM/yyyy"));
}

    
    private void loadVendedorData() {
        VendedorDAO vendedorDAO = new VendedorDAO();
        Vendedor vendedor = vendedorDAO.obtenerVendedorPorId(idVendedor);
        if (vendedor != null) {
            for (int i = 0; i < cmbUsuario.getItemCount(); i++) {
                Usuario user = cmbUsuario.getItemAt(i);
                if (user.getIdUsuario() == vendedor.getIdUsuario()) {
                    cmbUsuario.setSelectedIndex(i);
                    break;
                }
            }
            spnInicio.setValue(vendedor.getFechaInicio());
            spnFin.setValue(vendedor.getFechaFin());
            txtRazon.setText(vendedor.getRazonSocial());
        }
    }
    private void configureUsuarios() {
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        List<Usuario> usuarios = usuarioDAO.obtenerUsuarios();

        if ("Admin".equalsIgnoreCase(usuario.getRol())) {
            for (Usuario user : usuarios) {
                cmbUsuario.addItem(user);
            }
        } else {
            for (Usuario user : usuarios) {
                if (user.getIdUsuario() == usuario.getIdUsuario()) {
                    cmbUsuario.addItem(user);
                    break;
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        spnInicio = new javax.swing.JSpinner();
        spnFin = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        lblFin = new javax.swing.JLabel();
        lblRazon = new javax.swing.JLabel();
        txtRazon = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panel1.setBackground(new java.awt.Color(175, 18, 128));
        panel1.setMinimumSize(new java.awt.Dimension(390, 360));
        panel1.setPreferredSize(new java.awt.Dimension(390, 360));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spnInicio.setModel(new javax.swing.SpinnerDateModel());
        spnInicio.setBorder(null);
        panel1.add(spnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 145, 220, 30));

        spnFin.setModel(new javax.swing.SpinnerDateModel());
        spnFin.setPreferredSize(new java.awt.Dimension(64, 22));
        spnFin.setVerifyInputWhenFocusTarget(false);
        panel1.add(spnFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 220, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TAMBOmain.png"))); // NOI18N
        jLabel1.setRequestFocusEnabled(false);
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 160, 60));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario:");
        panel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblInicio.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblInicio.setForeground(new java.awt.Color(255, 255, 255));
        lblInicio.setText("Fecha Inicio:");
        panel1.add(lblInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblFin.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblFin.setForeground(new java.awt.Color(255, 255, 255));
        lblFin.setText("Fecha Fin:");
        panel1.add(lblFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 195, -1, -1));

        lblRazon.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblRazon.setForeground(new java.awt.Color(255, 255, 255));
        lblRazon.setText("Razón Social:");
        panel1.add(lblRazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        txtRazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonActionPerformed(evt);
            }
        });
        panel1.add(txtRazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 220, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 238, 0));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-eliminar-24 (1).png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(255, 238, 0));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-lazo-marcapáginas-24.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazonActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
                int idUsuario = ((Usuario) cmbUsuario.getSelectedItem()).getIdUsuario();
                Date fechaInicio = (Date) spnInicio.getValue();
                Date fechaFin = (Date) spnFin.getValue();
                String razonSocial = txtRazon.getText();

                Vendedor nuevoVendedor = new Vendedor(idVendedor, idUsuario, fechaInicio, fechaFin, razonSocial);
                VendedorDAO vendedorDAO = new VendedorDAO();
                int errorCode;

                if (isModify) {
                    errorCode = vendedorDAO.modificarVendedor(nuevoVendedor);
                } else {
                    errorCode = vendedorDAO.insertarVendedor(nuevoVendedor);
                }

                if (errorCode == 0) {
                    JOptionPane.showMessageDialog(VendedorRegister_Modf.this,
                            isModify ? "Vendedor modificado exitosamente." : "Vendedor registrado exitosamente.",
                            "Éxito",
                            JOptionPane.INFORMATION_MESSAGE);
                    if (vendedorView != null) {
                        vendedorView.refreshVendedores();
                    }
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(VendedorRegister_Modf.this,
                            isModify ? "Error: Vendedor no encontrado." : "Error: No se pudo registrar el vendedor.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

                dispose();  
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFin;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblRazon;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panel1;
    private javax.swing.JSpinner spnFin;
    private javax.swing.JSpinner spnInicio;
    private javax.swing.JTextField txtRazon;
    // End of variables declaration//GEN-END:variables
}
