
package view.Main;


import dto.Usuario;
import view.Usuario.UsuarioView;
import view.Vendedor.VendedorView;
import view.Login.LoginView;
import view.Producto.ProductoInventarioView;
import view.Movimiento.MovimientoInventarioView;
import view.Venta.VentaView;

import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Eduardo
 */
public class MainView extends javax.swing.JFrame {
    private final Usuario usuario;
    /**
     * Creates new form MainVista
     */
    public MainView(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        inicio();
        setTitle("Sistema de Ventas Tambo");
        setLocationRelativeTo(null); 
        showUsuarioView();
    }
    private void inicio() {
        btnUsuarios.addActionListener(e -> {
            showUsuarioView();
        });

        btnVendedores.addActionListener(e -> {
            showVendedorView();
        });
        
        btnProductos.addActionListener(e -> {
            showProductoView();
        });
        
        btnVenta.addActionListener(e -> {
            showVentaView();
        });
        
        btnInven.addActionListener(e -> {
            showMovimientoView();
        });
        
        btnSalir.addActionListener(e -> {
            dispose(); 
            new LoginView().setVisible(true); 
        });
    }
    
   private void showUsuarioView() {
        conPanel.removeAll();
        conPanel.add(new UsuarioView(usuario), BorderLayout.CENTER);
        conPanel.revalidate();
        conPanel.repaint();
    }
    
    private void showVendedorView() 
    {
        conPanel.removeAll();
        conPanel.add(new VendedorView(usuario), BorderLayout.CENTER);
        conPanel.revalidate();
        conPanel.repaint();
    }
    
    private void showProductoView() 
    {
        conPanel.removeAll();
        conPanel.add(new ProductoInventarioView(usuario), BorderLayout.CENTER);
        conPanel.revalidate();
        conPanel.repaint();
    }
    
    private void showMovimientoView() 
    {
        conPanel.removeAll();
        conPanel.add(new MovimientoInventarioView(usuario), BorderLayout.CENTER);
        conPanel.revalidate();
        conPanel.repaint();
    }
    
     private void showVentaView() 
    {
        conPanel.removeAll();
        conPanel.add(new VentaView(usuario), BorderLayout.CENTER);
        conPanel.revalidate();
        conPanel.repaint();
    }
    /**
     * @param args the command line argumen
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnVendedores = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnInven = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblLogo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        conPanel.setLayout(new java.awt.BorderLayout());

        menuPanel.setBackground(new java.awt.Color(175, 18, 128));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsuarios.setBackground(new java.awt.Color(255, 238, 0));
        btnUsuarios.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(175, 18, 128));
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBorder(null);
        menuPanel.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 150, 110, 33));

        btnVendedores.setBackground(new java.awt.Color(255, 238, 0));
        btnVendedores.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnVendedores.setForeground(new java.awt.Color(175, 18, 128));
        btnVendedores.setText("Vendedores");
        btnVendedores.setBorder(null);
        btnVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedoresActionPerformed(evt);
            }
        });
        menuPanel.add(btnVendedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 200, 110, 33));

        btnProductos.setBackground(new java.awt.Color(255, 238, 0));
        btnProductos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(175, 18, 128));
        btnProductos.setText("Productos");
        btnProductos.setBorder(null);
        menuPanel.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 250, 110, 33));

        btnInven.setBackground(new java.awt.Color(255, 238, 0));
        btnInven.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnInven.setForeground(new java.awt.Color(175, 18, 128));
        btnInven.setText("Mov. Inventario");
        btnInven.setBorder(null);
        menuPanel.add(btnInven, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 350, 110, 33));

        btnVenta.setBackground(new java.awt.Color(255, 238, 0));
        btnVenta.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnVenta.setForeground(new java.awt.Color(175, 18, 128));
        btnVenta.setText("Venta");
        btnVenta.setBorder(null);
        menuPanel.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 300, 110, 33));

        btnSalir.setBackground(new java.awt.Color(255, 238, 0));
        btnSalir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(175, 18, 128));
        btnSalir.setText("Cerrar sesión");
        btnSalir.setBorder(null);
        menuPanel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 460, 110, 33));

        lblLogo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TAMBOmain.png"))); // NOI18N
        menuPanel.add(lblLogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(232, Short.MAX_VALUE)
                    .addComponent(conPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(42, Short.MAX_VALUE)
                    .addComponent(conPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVendedoresActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInven;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVendedores;
    private javax.swing.JButton btnVenta;
    private javax.swing.JPanel conPanel;
    private javax.swing.JLabel lblLogo3;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
